language: generic

script:
  - cd brs-debian
  - ./package.sh
  - cd ../

deploy:
  provider: releases
  api_key: $API_KEY
  file: "brs-debian/burstcoin-wallet.deb"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false
